### PR TITLE
Add checkstyle configuration for Java

### PR DESCRIPTION
**Pull request by enqueue**

### CODE REVIEW

**Review by HardTy — CHANGES_REQUESTED** [review]
We should place the checkstyle configurations in the directory of the other linter configurations or configure the super-linters checkstyle env to use it in this place. Just to have super-linter complete.

**Comment by enqueue** [comment]
> We should place the checkstyle configurations in the directory of the other linter configurations or configure the super-linters checkstyle env to use it in this place. Just to have super-linter complete.

All Java projects use the checkstyle gradle plugin to perform these checks. The goal of this PR was to make the Riege rules available for use in these scripts.

Trying to integrate this into some super-linter configuration might be interesting, but you would also have to teach every developer how to run this locally. So I would not do this now.

Perhaps we can do both, I will see.

**Comment by wiebeck** [comment]
> > We should place the checkstyle configurations in the directory of the other linter configurations or configure the super-linters checkstyle env to use it in this place. Just to have super-linter complete.
> 
> All Java projects use the checkstyle gradle plugin to perform these checks. The goal of this PR was to make the Riege rules available for use in these scripts.
> 
> Trying to integrate this into some super-linter configuration might be interesting, but you would also have to teach every developer how to run this locally. So I would not do this now.
> 
> Perhaps we can do both, I will see.

Maybe the best would be to change the default path for linter config files to the root of the repository....
```
LINTER_RULES_PATH: /
```
...and then reference the files as follows:
```
JAVA_FILE_NAME: java/checkstyle/checkstyle.xml
```
And the same for all other linters we have custom config for. The question is if filnames with paths are valid. All the examples only have filenames, not paths in them.

Reference: https://github.com/github/super-linter/blob/main/docs/using-rules-files.md

**Review by wiebeck — APPROVED** [review]

**Review by HardTy — APPROVED** [review]
LGTM

**Pull request merged**
